# Site settings
title: Vancouver Joint Statistics Seminar
tag_text: vanjss
description: Information about the SFU-UBC Joint Statistics Seminar
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
