# Site settings
title: Vancouver Joint Statistics Seminar
tag_text: Vancouver Joint Statistics Seminar
description: Information about the SFU-UBC Joint Statistics Seminar
url: "http://vanjss.ca"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
