# Dependencies
plugins: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Vancouver Joint Statistics Seminar
description:         A semi-annual Joint Statistics Seminar between Simon Fraser University and the University of British Columbia
url:                 http://vanjss.ca
baseurl:             ''
paginate:            5


# Custom vars
version:             1.0.0
